### ISSUE TITLE
Mais dois novos probleminhas...

### ISSUE THREAD

**Issue by mlizander** [leandroferreirama/api-itau#4]
1 - Na classe Pessoa, no método setNomePessoa o uso de str_replace está invertido
Ao invés de str_replace($busca, $substitui, $nome), está str_replace($substitui, $busca, $nome)
Isso está fazendo com que os caracteres não acentuados passam a ser acentuados, o que deveria ser o contrário, retirar a acentuação.
Embora não atrapalhe o registro do boleto, trocar MARCUS por MÁRCÚS, não foi muito legal (rsrs)

2 - Na classe Endereco, no método textClearSpecialChar, a regex está eliminando espaços em branco no endereço...
Ao invés de return preg_replace("/[^\w]/", "", $value);
Deveria ser return preg_replace("/[^\w\s]/", "", $value);

**Comment by mlizander** [comment]
Acho que cheguei tarde... vi que vc já corrigiu...rs

**Comment by leandroferreirama** [comment]
Esses itens foram corrigidos na versão 2.1.19 Foi implementada uma nova classe para tratamento das strings.
